apiVersion: v1
kind: Service
metadata:
  name: classroom-ui-nodeport
spec:
  type: NodePort
  ports:
    - nodePort: 31317
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: classroom-ui
