apiVersion: v1
kind: Service
metadata:
  labels:
    name: classroom-ui-service
spec:
  type: ClusterIP
  ports:
    - name: classroom-ui-port
      port: 4200
      protocol: TCP
      targetPort: 4200
  selector:
    app: classroom-ui
