apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: load-balancer-service-0
  name: loadbalancer-service
spec:
  type: LoadBalancer
  ports:
    - name: load-balancer-service-port
      port: 80
      protocol: TCP
  selector:
    deployment-label-key: classroom-ui-deployment-0
