apiVersion: v1
kind: Service
metadata:
  labels:
  name: classroom-ui
spec:
  type: ClusterIP
  ports:
    - name: classroom-ui-port
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: classroom-ui
