apiVersion: apps/v1
kind: Deployment
metadata:
  name: classroom-ui
spec:
  selector:
    matchLabels:
      name: classroom-ui
  replicas: 1
  template:
    metadata:
      labels:
        name: classroom-ui
    spec:
      containers:
        - name: classroom-ui
          image: alexc/classroomui:latest
          imagePullPolicy: Never
#          ports:
#            - containerPort: 80
